sudo: required 
dist: xenial 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_DISTRO=kinetic
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=.rosinstall
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_REPO=ros 
    - ROS_REPO=ros-shadow-fixed
script: 
  - source .it_ci_config/travis.sh